# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59a7802c2c7f29663805bcf94186f569303d014884dcd31ea3bf5638890686acd37fd856f15e939ee21961e30edd91441e6b0a4f0fee4cf7cf76e9ab0ad21b4a

test:
  secret_key_base: 451e98e9fbbefdd3b3f3ec0c76c08be2bd71f3ce5d2937aa2f2e176fc6497edf2d7913584188cddc9612344ac24e8e4d53a652510caf1dd0c906c6b3f129b055

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
